# Site
name: "snap:bit"
title: "snap:bit"
description: "Combine BBC micro:bit with Snap Circuits"
meta_description: "Combine BBC micro:bit with Snap Circuits."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
email: 'office@snapbit.org'
google_analytics: 'UA-144649996-1'

collections:
  projects:
    output: true
    permalink: /:collection/:title.html

# Plugins
plugins: 
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-redirect-from
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
pagination:
  enabled: false
  collection: 'projects'
  per_page: 6
  permalink: '/projects/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
    
# Other
markdown: kramdown
highlighter: rouge

# Exclude these files from the build process results.
# Prevents them from showing up in the master branch which 
# is the live site.
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile